security:
    providers:
        #in_memory: { memory: ~ }
        our_db_provider:
            entity:
                class: App\Entity\Core\User
                property: username

    encoders:
        # for registration
        App\Entity\Core\User: bcrypt
        # for login
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost:      15

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            http_basic: ~ # to have the confirm login message alert
            provider: our_db_provider

            form_login:
                login_path: login
                check_path: login

            logout:
                path: /logout
                target: /

        secured_area:
            form_login:
                csrf_token_generator: security.csrf.token_manager

    # activate different ways to authenticate

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
            #require ROLE_ADMIN for /admin*
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }


#### DOCUMENTATION ###
 # https://symfony.com/doc/current/cookbook/security/form_login_setup.html
 # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
# https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate



