security:
    # https://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        #in_memory: { memory: ~ }
        our_db_provider:
            entity:
                class: App\Entity\Core\User
                property: username

    encoders:
        App\Entity\Core\User: bcrypt
            #algorithm:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost:      15

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            #pattern: ^/
            http_basic: ~ # to have a confirm log alert
            provider: our_db_provider

            form_login:
                login_path: login
                check_path: login

        # https://symfony.com/doc/current/cookbook/security/form_login_setup.html
        secured_area:
            form_login:
                csrf_token_generator: security.csrf.token_manager

            # activate different ways to authenticate
    access_control:
            #require ROLE_ADMIN for /admin*
            - { path: ^/admin, roles: ROLE_ADMIN }

            # http_basic: ~
            # https://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate



